import os
import sys
import json
import shutil
import threading
import http.server
import socketserver
import webbrowser
import tkinter as tk
from tkinter import ttk, messagebox, filedialog, simpledialog
from PIL import Image, ImageTk

# Directory configuration
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CATEGORIES_DIR = os.path.join(SCRIPT_DIR, "categories")
MANIFEST_FILE = os.path.join(SCRIPT_DIR, "categories.json")
DATA_JS_FILE = os.path.join(SCRIPT_DIR, "categories-data.js")
DEFAULT_PORT = 8000

# Supported image extensions
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".bmp"}

class GalleryAdminApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Developer Admin Panel - Category Image Gallery")
        
        # Fully responsive initial setup
        self.root.geometry("1100x680")
        self.root.minsize(800, 500)

        # Allow root window rows and columns to stretch dynamically
        self.root.grid_rowconfigure(1, weight=1)
        self.root.grid_columnconfigure(0, weight=1)

        self.server_thread = None
        self.httpd = None
        self.server_running = False
        self.current_preview_photo = None

        self.init_directories()
        self.setup_styles()
        self.create_widgets()
        self.refresh_all()

    def init_directories(self):
        """Ensure categories root directory exists."""
        if not os.path.exists(CATEGORIES_DIR):
            os.makedirs(CATEGORIES_DIR)
        self.sync_manifest()

    def sync_manifest(self):
        """Scan categories folder and generate categories.json and categories-data.js manifests."""
        manifest_data = []
        if os.path.exists(CATEGORIES_DIR):
            categories = sorted([
                d for d in os.listdir(CATEGORIES_DIR)
                if os.path.isdir(os.path.join(CATEGORIES_DIR, d))
            ])

            for cat in categories:
                cat_path = os.path.join(CATEGORIES_DIR, cat)
                images = sorted([
                    f for f in os.listdir(cat_path)
                    if os.path.isfile(os.path.join(cat_path, f)) and os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
                ])
                manifest_data.append({
                    "category": cat,
                    "images": images
                })

        # Save JSON manifest for HTTP server environments
        with open(MANIFEST_FILE, "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, indent=2)

        # Save JS data file for direct standalone file:// execution in any browser
        with open(DATA_JS_FILE, "w", encoding="utf-8") as f:
            f.write("// Auto-generated by admin_app.py - Allows index.html to run directly via file://\n")
            f.write(f"window.GALLERY_DATA = {json.dumps(manifest_data, indent=2)};\n")

        return manifest_data

    def setup_styles(self):
        """Configure sleek dark-mode ttk styles."""
        self.style = ttk.Style()
        self.style.theme_use("clam")

        # Dark Modern Palette
        BG_COLOR = "#0f172a"        # Deep slate background
        PANEL_BG = "#1e293b"        # Card / panel background
        CARD_BG = "#0f172a"         # Inner dark card background
        PRIMARY = "#3b82f6"         # Electric blue
        PRIMARY_HOVER = "#2563eb"   # Darker blue
        DANGER = "#ef4444"          # Crimson red
        DANGER_HOVER = "#dc2626"    # Darker red
        SUCCESS = "#10b981"         # Emerald green
        TEXT_MAIN = "#f8fafc"       # Bright white text
        TEXT_MUTED = "#94a3b8"      # Light grey text

        self.root.configure(bg=BG_COLOR)

        self.style.configure(".", background=BG_COLOR, foreground=TEXT_MAIN, font=("Segoe UI", 10))
        self.style.configure("TFrame", background=BG_COLOR)
        self.style.configure("Panel.TFrame", background=PANEL_BG, relief="flat")
        self.style.configure("Card.TFrame", background=CARD_BG, relief="flat")
        self.style.configure("Status.TFrame", background="#0b0f19")

        # Labels
        self.style.configure("Header.TLabel", font=("Segoe UI", 16, "bold"), foreground=TEXT_MAIN, background=BG_COLOR)
        self.style.configure("SubHeader.TLabel", font=("Segoe UI", 11, "bold"), foreground=PRIMARY, background=PANEL_BG)
        self.style.configure("Muted.TLabel", font=("Segoe UI", 9), foreground=TEXT_MUTED, background=BG_COLOR)
        self.style.configure("PanelMuted.TLabel", font=("Segoe UI", 9), foreground=TEXT_MUTED, background=PANEL_BG)
        self.style.configure("CardMuted.TLabel", font=("Segoe UI", 9), foreground=TEXT_MUTED, background=CARD_BG)
        self.style.configure("CardHeader.TLabel", font=("Segoe UI", 10, "bold"), foreground=TEXT_MAIN, background=CARD_BG)
        self.style.configure("Status.TLabel", font=("Segoe UI", 9, "italic"), foreground=TEXT_MUTED, background="#0b0f19")

        # Custom Buttons
        self.style.configure("TButton", font=("Segoe UI", 9, "bold"), padding=7, relief="flat", borderwidth=0)
        
        self.style.configure("Primary.TButton", background=PRIMARY, foreground="white")
        self.style.map("Primary.TButton", background=[("active", PRIMARY_HOVER)])
        
        self.style.configure("Danger.TButton", background=DANGER, foreground="white")
        self.style.map("Danger.TButton", background=[("active", DANGER_HOVER)])

        self.style.configure("Secondary.TButton", background="#334155", foreground=TEXT_MAIN)
        self.style.map("Secondary.TButton", background=[("active", "#475569")])

        self.style.configure("Server.TButton", background=SUCCESS, foreground="white")
        self.style.map("Server.TButton", background=[("active", "#059669")])

        # Treeview styling
        self.style.configure("Treeview", 
                             background=PANEL_BG, 
                             foreground=TEXT_MAIN, 
                             fieldbackground=PANEL_BG, 
                             rowheight=30, 
                             font=("Segoe UI", 10),
                             borderwidth=0)
        self.style.configure("Treeview.Heading", 
                             font=("Segoe UI", 10, "bold"), 
                             background="#334155", 
                             foreground=TEXT_MAIN,
                             relief="flat")
        self.style.map("Treeview", 
                       background=[("selected", PRIMARY)], 
                       foreground=[("selected", "white")])

    def create_widgets(self):
        # ----------------- Top Header Bar -----------------
        header_frame = ttk.Frame(self.root)
        header_frame.grid(row=0, column=0, sticky="ew", padx=20, pady=(15, 5))

        title_lbl = ttk.Label(header_frame, text="⚡ Gallery Developer Dashboard", style="Header.TLabel")
        title_lbl.pack(side=tk.LEFT)

        subtitle_lbl = ttk.Label(header_frame, text="Manage image categories, labels & live previews", style="Muted.TLabel")
        subtitle_lbl.pack(side=tk.LEFT, padx=15, pady=(4, 0))

        # ----------------- Main Responsive Paned View -----------------
        paned = ttk.PanedWindow(self.root, orient=tk.HORIZONTAL)
        paned.grid(row=1, column=0, sticky="nsew", padx=20, pady=10)

        # Left Panel: Categories List
        left_panel = ttk.Frame(paned, style="Panel.TFrame")
        paned.add(left_panel, weight=1)

        left_panel.grid_rowconfigure(1, weight=1)
        left_panel.grid_columnconfigure(0, weight=1)

        cat_header_frame = ttk.Frame(left_panel, style="Panel.TFrame")
        cat_header_frame.grid(row=0, column=0, sticky="ew", padx=12, pady=(12, 6))

        ttk.Label(cat_header_frame, text="📁 Categories Directory", style="SubHeader.TLabel").pack(side=tk.LEFT)

        # Treeview Container
        tree_frame = ttk.Frame(left_panel, style="Panel.TFrame")
        tree_frame.grid(row=1, column=0, sticky="nsew", padx=12, pady=4)
        tree_frame.grid_rowconfigure(0, weight=1)
        tree_frame.grid_columnconfigure(0, weight=1)

        self.cat_tree = ttk.Treeview(tree_frame, columns=("count",), show="tree headings", selectmode="browse")
        self.cat_tree.heading("#0", text="Category Name", anchor=tk.W)
        self.cat_tree.heading("count", text="Images", anchor=tk.CENTER)
        self.cat_tree.column("#0", stretch=True, minwidth=120)
        self.cat_tree.column("count", width=65, stretch=False, anchor=tk.CENTER)
        
        cat_scroll = ttk.Scrollbar(tree_frame, orient=tk.VERTICAL, command=self.cat_tree.yview)
        self.cat_tree.configure(yscrollcommand=cat_scroll.set)
        
        self.cat_tree.grid(row=0, column=0, sticky="nsew")
        cat_scroll.grid(row=0, column=1, sticky="ns")

        self.cat_tree.bind("<<TreeviewSelect>>", self.on_category_select)

        # Category Buttons
        cat_btn_frame = ttk.Frame(left_panel, style="Panel.TFrame")
        cat_btn_frame.grid(row=2, column=0, sticky="ew", padx=12, pady=12)

        ttk.Button(cat_btn_frame, text="➕ New Category", style="Primary.TButton", command=self.create_category).pack(fill=tk.X, pady=3)
        ttk.Button(cat_btn_frame, text="✏️ Rename Selected", style="Secondary.TButton", command=self.rename_category).pack(fill=tk.X, pady=3)
        ttk.Button(cat_btn_frame, text="🗑️ Delete Selected", style="Danger.TButton", command=self.delete_category).pack(fill=tk.X, pady=3)

        # Right Panel: Image Management & Live Preview
        right_panel = ttk.Frame(paned, style="Panel.TFrame")
        paned.add(right_panel, weight=3)

        right_panel.grid_rowconfigure(1, weight=1)
        right_panel.grid_columnconfigure(0, weight=1)

        img_header_frame = ttk.Frame(right_panel, style="Panel.TFrame")
        img_header_frame.grid(row=0, column=0, sticky="ew", padx=12, pady=(12, 6))

        self.lbl_selected_cat = ttk.Label(img_header_frame, text="Select a Category", style="SubHeader.TLabel")
        self.lbl_selected_cat.pack(side=tk.LEFT)

        # Main Content Area: Split into Image List (Left) and Image Preview (Right)
        img_content_frame = ttk.Frame(right_panel, style="Panel.TFrame")
        img_content_frame.grid(row=1, column=0, sticky="nsew", padx=12, pady=4)
        img_content_frame.grid_rowconfigure(0, weight=1)
        img_content_frame.grid_columnconfigure(0, weight=3)
        img_content_frame.grid_columnconfigure(1, weight=2)

        # 1. Image Listbox Container (Left Column)
        listbox_container = ttk.Frame(img_content_frame, style="Panel.TFrame")
        listbox_container.grid(row=0, column=0, sticky="nsew", padx=(0, 8))
        listbox_container.grid_rowconfigure(0, weight=1)
        listbox_container.grid_columnconfigure(0, weight=1)

        self.img_listbox = tk.Listbox(
            listbox_container, 
            font=("Segoe UI", 10), 
            selectmode=tk.SINGLE, 
            bg="#0f172a", 
            fg="#f8fafc", 
            selectbackground="#3b82f6", 
            selectforeground="#ffffff", 
            bd=0, 
            highlightthickness=1,
            highlightbackground="#334155"
        )
        img_scroll = ttk.Scrollbar(listbox_container, orient=tk.VERTICAL, command=self.img_listbox.yview)
        self.img_listbox.configure(yscrollcommand=img_scroll.set)

        self.img_listbox.grid(row=0, column=0, sticky="nsew")
        img_scroll.grid(row=0, column=1, sticky="ns")

        # Bind image selection and double click
        self.img_listbox.bind("<<ListboxSelect>>", self.on_image_select)
        self.img_listbox.bind("<Double-Button-1>", lambda e: self.rename_image())

        # 2. Image Preview Panel (Right Column)
        preview_panel = ttk.Frame(img_content_frame, style="Card.TFrame")
        preview_panel.grid(row=0, column=1, sticky="nsew")
        preview_panel.grid_rowconfigure(1, weight=1)
        preview_panel.grid_columnconfigure(0, weight=1)

        # Preview Header
        prev_head_frame = ttk.Frame(preview_panel, style="Card.TFrame")
        prev_head_frame.grid(row=0, column=0, sticky="ew", padx=10, pady=(8, 4))
        ttk.Label(prev_head_frame, text="🔍 Image Preview & Details", style="CardHeader.TLabel").pack(side=tk.LEFT)

        # Preview Image Box (Tkinter Label acting as thumbnail display canvas)
        self.preview_lbl = tk.Label(
            preview_panel,
            text="No image selected\n\nClick an image to preview",
            font=("Segoe UI", 9),
            bg="#0b0f19",
            fg="#64748b",
            relief="flat",
            bd=0,
            highlightthickness=1,
            highlightbackground="#334155"
        )
        self.preview_lbl.grid(row=1, column=0, sticky="nsew", padx=10, pady=6)

        # Preview Metadata Details
        meta_frame = ttk.Frame(preview_panel, style="Card.TFrame")
        meta_frame.grid(row=2, column=0, sticky="ew", padx=10, pady=(2, 8))

        self.lbl_preview_name = ttk.Label(meta_frame, text="Name: —", style="CardHeader.TLabel", wraplength=230)
        self.lbl_preview_name.pack(anchor="w", pady=(0, 2))

        self.lbl_preview_dims = ttk.Label(meta_frame, text="Resolution: —", style="CardMuted.TLabel")
        self.lbl_preview_dims.pack(anchor="w")

        self.lbl_preview_size = ttk.Label(meta_frame, text="Size: —", style="CardMuted.TLabel")
        self.lbl_preview_size.pack(anchor="w")

        # Image Action Buttons
        img_btn_frame = ttk.Frame(right_panel, style="Panel.TFrame")
        img_btn_frame.grid(row=2, column=0, sticky="ew", padx=12, pady=12)
        img_btn_frame.grid_columnconfigure(0, weight=1)
        img_btn_frame.grid_columnconfigure(1, weight=1)
        img_btn_frame.grid_columnconfigure(2, weight=1)

        self.btn_upload = ttk.Button(img_btn_frame, text="📤 Upload Images", style="Primary.TButton", command=self.upload_images, state=tk.DISABLED)
        self.btn_upload.grid(row=0, column=0, sticky="ew", padx=(0, 4))

        self.btn_rename_img = ttk.Button(img_btn_frame, text="✏️ Edit Image Label", style="Secondary.TButton", command=self.rename_image, state=tk.DISABLED)
        self.btn_rename_img.grid(row=0, column=1, sticky="ew", padx=4)

        self.btn_delete_img = ttk.Button(img_btn_frame, text="❌ Delete Image", style="Danger.TButton", command=self.delete_images, state=tk.DISABLED)
        self.btn_delete_img.grid(row=0, column=2, sticky="ew", padx=(4, 0))

        # ----------------- Bottom Action Controls -----------------
        bottom_frame = ttk.Frame(self.root)
        bottom_frame.grid(row=2, column=0, sticky="ew", padx=20, pady=(4, 8))

        self.btn_open_web = ttk.Button(bottom_frame, text="🚀 Open Gallery (Direct/Browser)", style="Primary.TButton", command=self.open_webpage)
        self.btn_open_web.pack(side=tk.LEFT)

        self.btn_server = ttk.Button(bottom_frame, text=f"🌐 Optional: Launch Server ({DEFAULT_PORT})", style="Secondary.TButton", command=self.toggle_web_server)
        self.btn_server.pack(side=tk.LEFT, padx=8)

        # Footer Status Strip
        status_strip = ttk.Frame(self.root, style="Status.TFrame")
        status_strip.grid(row=3, column=0, sticky="ew")

        self.lbl_status = ttk.Label(status_strip, text="System Ready", style="Status.TLabel")
        self.lbl_status.pack(side=tk.LEFT, padx=15, pady=3)

    def set_status(self, text):
        self.lbl_status.config(text=f"Status: {text}")

    def get_selected_category_name(self):
        selected = self.cat_tree.selection()
        if selected:
            return self.cat_tree.item(selected[0], "text")
        return None

    def get_selected_image_name(self):
        selected_indices = self.img_listbox.curselection()
        if selected_indices:
            return self.img_listbox.get(selected_indices[0]).strip()
        return None

    def refresh_all(self, keep_img_selection=None):
        """Refresh category list, image list, and sync JSON manifest."""
        manifest = self.sync_manifest()
        
        for item in self.cat_tree.get_children():
            self.cat_tree.delete(item)

        selected_cat = self.get_selected_category_name()
        reselect_item = None

        for cat_info in manifest:
            cat_name = cat_info["category"]
            img_count = len(cat_info["images"])
            item_id = self.cat_tree.insert("", tk.END, text=cat_name, values=(img_count,))
            if cat_name == selected_cat:
                reselect_item = item_id

        if reselect_item:
            self.cat_tree.selection_set(reselect_item)
            self.cat_tree.see(reselect_item)
            self.on_category_select(None, target_image=keep_img_selection)
        else:
            self.on_category_select(None)

        self.set_status("Manifests synced (categories.json & categories-data.js).")

    def on_category_select(self, event, target_image=None):
        cat_name = self.get_selected_category_name()
        self.img_listbox.delete(0, tk.END)
        self.clear_preview()

        if cat_name:
            self.lbl_selected_cat.config(text=f"🖼️ Images in '{cat_name}'")
            self.btn_upload.config(state=tk.NORMAL)
            self.btn_rename_img.config(state=tk.DISABLED)
            self.btn_delete_img.config(state=tk.DISABLED)

            cat_path = os.path.join(CATEGORIES_DIR, cat_name)
            if os.path.exists(cat_path):
                images = sorted([
                    f for f in os.listdir(cat_path)
                    if os.path.isfile(os.path.join(cat_path, f)) and os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
                ])
                reselect_idx = None
                for idx, img in enumerate(images):
                    self.img_listbox.insert(tk.END, f"  {img}")
                    if target_image and img == target_image:
                        reselect_idx = idx

                if reselect_idx is not None:
                    self.img_listbox.selection_set(reselect_idx)
                    self.img_listbox.see(reselect_idx)
                    self.on_image_select(None)
        else:
            self.lbl_selected_cat.config(text="Select a Category")
            self.btn_upload.config(state=tk.DISABLED)
            self.btn_rename_img.config(state=tk.DISABLED)
            self.btn_delete_img.config(state=tk.DISABLED)

    def on_image_select(self, event):
        """Handle selection of an image to render thumbnail and details."""
        cat_name = self.get_selected_category_name()
        img_name = self.get_selected_image_name()

        if cat_name and img_name:
            self.btn_rename_img.config(state=tk.NORMAL)
            self.btn_delete_img.config(state=tk.NORMAL)

            img_path = os.path.join(CATEGORIES_DIR, cat_name, img_name)
            self.update_image_preview(img_path)
        else:
            self.btn_rename_img.config(state=tk.DISABLED)
            self.btn_delete_img.config(state=tk.DISABLED)
            self.clear_preview()

    def clear_preview(self):
        """Clear the preview box and metadata labels."""
        self.preview_lbl.config(
            image="",
            text="No image selected\n\nClick an image to preview",
            fg="#64748b"
        )
        self.lbl_preview_name.config(text="Name: —")
        self.lbl_preview_dims.config(text="Resolution: —")
        self.lbl_preview_size.config(text="Size: —")
        self.current_preview_photo = None

    def update_image_preview(self, img_path):
        """Load and display image preview thumbnail with dimensions and size."""
        if not img_path or not os.path.exists(img_path):
            self.clear_preview()
            return

        try:
            with Image.open(img_path) as pil_img:
                orig_w, orig_h = pil_img.size
                img_format = pil_img.format or os.path.splitext(img_path)[1].upper().replace(".", "")

                # Calculate thumbnail fit within preview boundary (e.g. max 240x180)
                max_w, max_h = 240, 180
                
                # Copy and resize for thumbnail
                thumb = pil_img.copy()
                thumb.thumbnail((max_w, max_h), Image.Resampling.LANCZOS)
                
                photo = ImageTk.PhotoImage(thumb)
                self.current_preview_photo = photo  # Prevent garbage collection

                self.preview_lbl.config(image=photo, text="")

                # Format file size
                file_size_bytes = os.path.getsize(img_path)
                if file_size_bytes < 1024:
                    size_str = f"{file_size_bytes} B"
                elif file_size_bytes < 1024 * 1024:
                    size_str = f"{file_size_bytes / 1024:.1f} KB"
                else:
                    size_str = f"{file_size_bytes / (1024 * 1024):.2f} MB"

                file_name = os.path.basename(img_path)
                self.lbl_preview_name.config(text=f"Name: {file_name}")
                self.lbl_preview_dims.config(text=f"Resolution: {orig_w} × {orig_h} px")
                self.lbl_preview_size.config(text=f"Size: {size_str} ({img_format})")
        except Exception as e:
            self.preview_lbl.config(
                image="",
                text=f"Preview Unavailable\n({str(e)})",
                fg="#ef4444"
            )
            self.lbl_preview_name.config(text=f"Name: {os.path.basename(img_path)}")
            self.lbl_preview_dims.config(text="Resolution: —")
            self.lbl_preview_size.config(text="Size: —")
            self.current_preview_photo = None

    def rename_image(self):
        """Rename the selected image's filename/label."""
        cat_name = self.get_selected_category_name()
        old_img_name = self.get_selected_image_name()

        if not cat_name or not old_img_name:
            messagebox.showwarning("Warning", "Please select an image to rename.", parent=self.root)
            return

        old_base, old_ext = os.path.splitext(old_img_name)

        new_name = simpledialog.askstring(
            "Edit Image Label",
            f"Enter new name for '{old_img_name}':",
            initialvalue=old_img_name,
            parent=self.root
        )

        if not new_name:
            return

        new_name = new_name.strip()
        if not new_name or new_name == old_img_name:
            return

        # Ensure valid extension is preserved if user omitted it
        if not os.path.splitext(new_name)[1]:
            new_name += old_ext

        old_path = os.path.join(CATEGORIES_DIR, cat_name, old_img_name)
        new_path = os.path.join(CATEGORIES_DIR, cat_name, new_name)

        if os.path.exists(new_path):
            messagebox.showerror("Error", f"An image named '{new_name}' already exists in '{cat_name}'!", parent=self.root)
            return

        try:
            os.rename(old_path, new_path)
            self.refresh_all(keep_img_selection=new_name)
            self.set_status(f"Renamed '{old_img_name}' to '{new_name}'.")
            messagebox.showinfo("Success", f"Renamed image to '{new_name}'!", parent=self.root)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to rename image: {str(e)}", parent=self.root)

    def create_category(self):
        new_name = simpledialog.askstring("New Category", "Enter new category name:", parent=self.root)
        if not new_name:
            return

        new_name = new_name.strip()
        if not new_name:
            return

        cat_path = os.path.join(CATEGORIES_DIR, new_name)
        if os.path.exists(cat_path):
            messagebox.showerror("Error", f"Category '{new_name}' already exists!", parent=self.root)
            return

        try:
            os.makedirs(cat_path)
            self.refresh_all()
            for item in self.cat_tree.get_children():
                if self.cat_tree.item(item, "text") == new_name:
                    self.cat_tree.selection_set(item)
                    break
            messagebox.showinfo("Success", f"Category '{new_name}' created successfully!", parent=self.root)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to create category: {str(e)}", parent=self.root)

    def rename_category(self):
        old_name = self.get_selected_category_name()
        if not old_name:
            messagebox.showwarning("Warning", "Please select a category to rename.", parent=self.root)
            return

        new_name = simpledialog.askstring("Rename Category", f"Enter new name for category '{old_name}':", initialvalue=old_name, parent=self.root)
        if not new_name:
            return

        new_name = new_name.strip()
        if not new_name or new_name == old_name:
            return

        old_path = os.path.join(CATEGORIES_DIR, old_name)
        new_path = os.path.join(CATEGORIES_DIR, new_name)

        if os.path.exists(new_path):
            messagebox.showerror("Error", f"Category '{new_name}' already exists!", parent=self.root)
            return

        try:
            os.rename(old_path, new_path)
            self.refresh_all()
            for item in self.cat_tree.get_children():
                if self.cat_tree.item(item, "text") == new_name:
                    self.cat_tree.selection_set(item)
                    break
            messagebox.showinfo("Success", f"Renamed category to '{new_name}'!", parent=self.root)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to rename category: {str(e)}", parent=self.root)

    def delete_category(self):
        cat_name = self.get_selected_category_name()
        if not cat_name:
            messagebox.showwarning("Warning", "Please select a category to delete.", parent=self.root)
            return

        confirm = messagebox.askyesno("Confirm Delete", f"Are you sure you want to delete category '{cat_name}' and ALL its images?", parent=self.root)
        if not confirm:
            return

        cat_path = os.path.join(CATEGORIES_DIR, cat_name)
        try:
            shutil.rmtree(cat_path)
            self.refresh_all()
            messagebox.showinfo("Deleted", f"Category '{cat_name}' deleted.", parent=self.root)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to delete category: {str(e)}", parent=self.root)

    def upload_images(self):
        cat_name = self.get_selected_category_name()
        if not cat_name:
            messagebox.showwarning("Warning", "Please select a category first.", parent=self.root)
            return

        files = filedialog.askopenfilenames(
            title="Select Images to Upload",
            filetypes=[("Image Files", "*.png *.jpg *.jpeg *.webp *.gif *.svg *.bmp"), ("All Files", "*.*")],
            parent=self.root
        )

        if not files:
            return

        target_dir = os.path.join(CATEGORIES_DIR, cat_name)
        copied_count = 0
        last_uploaded = None

        for file_path in files:
            file_name = os.path.basename(file_path)
            target_path = os.path.join(target_dir, file_name)
            
            base, ext = os.path.splitext(file_name)
            counter = 1
            while os.path.exists(target_path):
                target_path = os.path.join(target_dir, f"{base}_{counter}{ext}")
                counter += 1

            try:
                shutil.copy2(file_path, target_path)
                copied_count += 1
                last_uploaded = os.path.basename(target_path)
            except Exception as e:
                print(f"Error copying {file_path}: {e}")

        self.refresh_all(keep_img_selection=last_uploaded)
        messagebox.showinfo("Success", f"Uploaded {copied_count} image(s) to '{cat_name}'.", parent=self.root)

    def delete_images(self):
        cat_name = self.get_selected_category_name()
        img_name = self.get_selected_image_name()

        if not cat_name or not img_name:
            messagebox.showwarning("Warning", "Please select an image to delete.", parent=self.root)
            return

        confirm = messagebox.askyesno("Confirm Delete", f"Delete selected image '{img_name}' from '{cat_name}'?", parent=self.root)
        if not confirm:
            return

        img_path = os.path.join(CATEGORIES_DIR, cat_name, img_name)
        if os.path.exists(img_path):
            try:
                os.remove(img_path)
            except Exception as e:
                print(f"Error removing {img_path}: {e}")

        self.refresh_all()
        self.clear_preview()

    def toggle_web_server(self):
        if not self.server_running:
            self.start_web_server()
        else:
            self.stop_web_server()

    def start_web_server(self):
        handler = http.server.SimpleHTTPRequestHandler
        
        class QuietHandler(handler):
            def log_message(self, format, *args):
                pass

        os.chdir(SCRIPT_DIR)
        
        try:
            self.httpd = socketserver.TCPServer(("", DEFAULT_PORT), QuietHandler)
            self.server_thread = threading.Thread(target=self.httpd.serve_forever, daemon=True)
            self.server_thread.start()
            self.server_running = True
            self.btn_server.config(text=f"🛑 Stop Server (Port {DEFAULT_PORT})", style="Danger.TButton")
            self.set_status(f"Server active at http://localhost:{DEFAULT_PORT}")
        except Exception as e:
            messagebox.showerror("Server Error", f"Failed to start local web server: {str(e)}", parent=self.root)

    def stop_web_server(self):
        if self.httpd:
            self.httpd.shutdown()
            self.httpd.server_close()
            self.server_running = False
            self.btn_server.config(text=f"🌐 Optional: Launch Server ({DEFAULT_PORT})", style="Secondary.TButton")
            self.set_status("Web server offline.")

    def open_webpage(self):
        if self.server_running:
            webbrowser.open(f"http://localhost:{DEFAULT_PORT}/index.html")
        else:
            index_path = os.path.join(SCRIPT_DIR, "index.html")
            webbrowser.open(f"file:///{index_path}")

if __name__ == "__main__":
    root = tk.Tk()
    app = GalleryAdminApp(root)
    root.mainloop()
