// Auto-generated by admin_app.py - Allows index.html to run directly via file://
window.GALLERY_DATA = [
  {
    "category": "Architecture",
    "images": [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.png"
    ]
  },
  {
    "category": "Nature",
    "images": [
      "33.jpg"
    ]
  },
  {
    "category": "Testing",
    "images": [
      "ORGINAL.png"
    ]
  },
  {
    "category": "Wallpapers",
    "images": []
  }
];
