// Auto-generated by admin_app.py - Allows index.html to run directly via file://
window.GALLERY_DATA = [
  {
    "category": "(ECA) Extra Curricular Activities",
    "images": [
      {
        "name": "1000108056.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108057.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108058.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108059.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108060.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108061.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108062.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108063.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108064.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108065.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108066.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108067.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108068.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108069.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108070.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108071.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108072.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108073.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108074.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108075.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108076.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108077.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108079.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108080.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108081.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108082.jpg",
        "date": "2026/09/02"
      }
    ]
  },
  {
    "category": "Cultural Activities",
    "images": []
  },
  {
    "category": "Meetings",
    "images": []
  },
  {
    "category": "Miscellaneous",
    "images": [
      {
        "name": "1000107863.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "111111111.jpeg",
        "date": "2026/09/02"
      },
      {
        "name": "Admission_open_Diploma_2082 (1) (1).png",
        "date": "2026/09/02"
      },
      {
        "name": "WhatsApp Image 2026-04-30 at 6.37.09 PM.jpeg",
        "date": "2026/09/02"
      },
      {
        "name": "school_new_logo (1).jpg",
        "date": "2026/09/02"
      },
      {
        "name": "see_2082_result_page-0001 (2).jpg",
        "date": "2026/09/02"
      },
      {
        "name": "slide4.jpg",
        "date": "2026/09/02"
      }
    ]
  },
  {
    "category": "Vistis",
    "images": [
      {
        "name": "1000108253.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108254.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108255.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "Institute Image.jpg",
        "date": "2026/09/02"
      }
    ]
  }
];
