// Auto-generated by admin_app.py - Allows index.html to run directly via file://
window.GALLERY_DATA = [
  {
    "category": "Testing",
    "images": [
      {
        "name": "1000105590.jpg",
        "date": "2026/09/01"
      },
      {
        "name": "1000108079.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108081.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108082.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "1000108592.jpg",
        "date": "2026/09/02"
      },
      {
        "name": "17882747568095202061645818358450.jpg",
        "date": "2026/09/01"
      },
      {
        "name": "4.png",
        "date": "2026/09/01"
      },
      {
        "name": "Institute Image.jpg",
        "date": "2026/09/01"
      }
    ]
  }
];
